version: '3'

services:
    gym-api-pg:
        image: bitnami/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=gym-api-docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=gym-api

